workflows:
 my-workflow:
  environment:
    node: latest
    npm: latest
    groups:
      - sauce_credentials
  scripts:
      - name: Run npm install
        script: npm install
      - name: cd wdio-example && npx wdio ./wdio.conf.js
        
  